### ISSUE TITLE
when i commit on modal,  i get 500 internal error.

### ISSUE THREAD

**Issue by fatihtas** [jetthoughts/remote_modals_demo#1]
Hi, 

when i submit my company form on a modal (`update_maps_and_address` method), i keep getting this error. 

It tries to render edit page:

>  ActionView::MissingTemplate (Missing template companies/edit...

it runs `render(*args)` method **twice** for ajax. and then gives` **500 error**   `
`Completed 500 Internal Server Error in 1266ms`

 ```
app/services/modal_responder.rb:26:in `render'
  app/controllers/application_controller.rb:106:in `respond_with_modal'
  app/controllers/companies_controller.rb:241:in `update_maps_and_address'
```

My _render_ and _respond_with_ modal methods are exactly same to yours
Any idea whats going on indeed?

**Comment by pftg** [comment]
@obliviusm please help

**Comment by fatihtas** [comment]
okay , i figured it has something to do with callbacks. 
cause when i delete `after_save :add_to_algolia on: [:create, : update_maps_and_address ]` on _company controller_, it works fine.. 
So, the after_save callback function is preventing it from working well. 
Considering this any idea how to work fine with callbacks ?

**Comment by obliviusm** [comment]
@fatihtas maybe problem is in the model? 
does it work without modal? 
code for modal doesn't do any saving. it only takes model, checks if it is valid and based on that renders partial. so it shouldnvt be connected with callbacks

**Comment by obliviusm** [comment]
or there is a problem when validation happens

**Comment by fatihtas** [comment]
Hi @obliviusm 
the problem started when I add,` after_save :add_to_algolia on: [:create, : update_maps_and_address ]` into my company model. 

add_to_algolia method works fine if I don't use modal forms, When i submit form via modal, then it gives 500 error. and if I delete after` after_save :add_to_algolia on: [:create, : update_maps_and_address ]`   modal works fine. 
Right now, I am trying to work on a sidekiq kinda solution so run `after_save` methods later on as a workaround. However, this is not a desired solution tbh. 

when I followed **`ModalResponder`**  methods via _byebug_ step by step, I have seen it goes to callbacks and somehow deletes `options` hash. and `args` array at one point. I couldn't figure out reason though and it is a very long chain tbh. so i can't copy paste since I don't know what part is really the problem related. 
 
As you have pointed out, it might be related to validations as well, but I have no idea how to probe it. my objects are valid as far as i can see. it is being saved and updated to algolia successfully if not using modal.

++ someone on medium blog post commented as well about this 500 error, but doesn't give any detail, so it is not only my problem i guess 
Thanks for your time
